### ISSUE TITLE
Play Store Error Report

### ISSUE THREAD

**Issue by rastating** [rastating/DroidBeard#71]
```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
at java.util.Collections.sort(Collections.java:1882)
at com.rastating.droidbeard.net.FetchShowTask.doInBackground(FetchShowTask.java:166)
at com.rastating.droidbeard.net.FetchShowTask.doInBackground(FetchShowTask.java:42)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
```

**Comment by rastating** [comment]
Fixed in 4115a9dc2a60be121b3b7278977cd02f8990a59e
